# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pubchemui.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSplitter, QWidget)

class Ui_Pubchem_Tools(object):
    def setupUi(self, Pubchem_Tools):
        if not Pubchem_Tools.objectName():
            Pubchem_Tools.setObjectName(u"Pubchem_Tools")
        Pubchem_Tools.resize(716, 500)
        Pubchem_Tools.setCursor(QCursor(Qt.ArrowCursor))
        Pubchem_Tools.setContextMenuPolicy(Qt.NoContextMenu)
        Pubchem_Tools.setLayoutDirection(Qt.LeftToRight)
        self.ConvertState = QLabel(Pubchem_Tools)
        self.ConvertState.setObjectName(u"ConvertState")
        self.ConvertState.setEnabled(True)
        self.ConvertState.setGeometry(QRect(240, 140, 71, 21))
        self.ConvertState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.ConvertState.setFrameShape(QFrame.WinPanel)
        self.ConvertState.setFrameShadow(QFrame.Plain)
        self.ConvertState.setAlignment(Qt.AlignCenter)
        self.Convert2DState = QLabel(Pubchem_Tools)
        self.Convert2DState.setObjectName(u"Convert2DState")
        self.Convert2DState.setGeometry(QRect(370, 240, 91, 21))
        self.Convert2DState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.Convert2DState.setFocusPolicy(Qt.NoFocus)
        self.Convert2DState.setContextMenuPolicy(Qt.PreventContextMenu)
        self.Convert2DState.setFrameShape(QFrame.WinPanel)
        self.Convert2DState.setAlignment(Qt.AlignCenter)
        self.Convert3DState = QLabel(Pubchem_Tools)
        self.Convert3DState.setObjectName(u"Convert3DState")
        self.Convert3DState.setGeometry(QRect(500, 240, 91, 21))
        self.Convert3DState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.Convert3DState.setFocusPolicy(Qt.NoFocus)
        self.Convert3DState.setContextMenuPolicy(Qt.PreventContextMenu)
        self.Convert3DState.setFrameShape(QFrame.WinPanel)
        self.Convert3DState.setAlignment(Qt.AlignCenter)
        self.AddCasState = QLabel(Pubchem_Tools)
        self.AddCasState.setObjectName(u"AddCasState")
        self.AddCasState.setEnabled(True)
        self.AddCasState.setGeometry(QRect(340, 140, 71, 21))
        self.AddCasState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.AddCasState.setFrameShape(QFrame.WinPanel)
        self.AddCasState.setFrameShadow(QFrame.Plain)
        self.AddCasState.setAlignment(Qt.AlignCenter)
        self.Save2DMolButton = QPushButton(Pubchem_Tools)
        self.Save2DMolButton.setObjectName(u"Save2DMolButton")
        self.Save2DMolButton.setGeometry(QRect(360, 180, 121, 24))
        self.Save3DMolButton = QPushButton(Pubchem_Tools)
        self.Save3DMolButton.setObjectName(u"Save3DMolButton")
        self.Save3DMolButton.setGeometry(QRect(490, 180, 121, 24))
        self.ConvertPicState = QLabel(Pubchem_Tools)
        self.ConvertPicState.setObjectName(u"ConvertPicState")
        self.ConvertPicState.setGeometry(QRect(280, 320, 91, 21))
        self.ConvertPicState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.ConvertPicState.setFocusPolicy(Qt.NoFocus)
        self.ConvertPicState.setContextMenuPolicy(Qt.PreventContextMenu)
        self.ConvertPicState.setFrameShape(QFrame.WinPanel)
        self.ConvertPicState.setAlignment(Qt.AlignCenter)
        self.splitter = QSplitter(Pubchem_Tools)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(60, 110, 571, 24))
        self.splitter.setOrientation(Qt.Horizontal)
        self.label = QLabel(self.splitter)
        self.label.setObjectName(u"label")
        font = QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setFrameShape(QFrame.NoFrame)
        self.label.setFrameShadow(QFrame.Raised)
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.splitter.addWidget(self.label)
        self.SelectCsvButton = QPushButton(self.splitter)
        self.SelectCsvButton.setObjectName(u"SelectCsvButton")
        self.splitter.addWidget(self.SelectCsvButton)
        self.SaveExcelButton = QPushButton(self.splitter)
        self.SaveExcelButton.setObjectName(u"SaveExcelButton")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveExcelButton.sizePolicy().hasHeightForWidth())
        self.SaveExcelButton.setSizePolicy(sizePolicy)
        self.splitter.addWidget(self.SaveExcelButton)
        self.AddCasToExcelButton = QPushButton(self.splitter)
        self.AddCasToExcelButton.setObjectName(u"AddCasToExcelButton")
        self.splitter.addWidget(self.AddCasToExcelButton)
        self.label_2 = QLabel(self.splitter)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.splitter.addWidget(self.label_2)
        self.splitter_2 = QSplitter(Pubchem_Tools)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(40, 210, 550, 24))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.label_3 = QLabel(self.splitter_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setFrameShape(QFrame.NoFrame)
        self.label_3.setFrameShadow(QFrame.Raised)
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.splitter_2.addWidget(self.label_3)
        self.SelectSdfButton = QPushButton(self.splitter_2)
        self.SelectSdfButton.setObjectName(u"SelectSdfButton")
        self.splitter_2.addWidget(self.SelectSdfButton)
        self.SelectExcelButton = QPushButton(self.splitter_2)
        self.SelectExcelButton.setObjectName(u"SelectExcelButton")
        self.splitter_2.addWidget(self.SelectExcelButton)
        self.SaveMol2DButton = QPushButton(self.splitter_2)
        self.SaveMol2DButton.setObjectName(u"SaveMol2DButton")
        sizePolicy.setHeightForWidth(self.SaveMol2DButton.sizePolicy().hasHeightForWidth())
        self.SaveMol2DButton.setSizePolicy(sizePolicy)
        self.splitter_2.addWidget(self.SaveMol2DButton)
        self.SaveMol3DButton = QPushButton(self.splitter_2)
        self.SaveMol3DButton.setObjectName(u"SaveMol3DButton")
        self.splitter_2.addWidget(self.SaveMol3DButton)
        self.splitter_4 = QSplitter(Pubchem_Tools)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setGeometry(QRect(60, 290, 480, 24))
        self.splitter_4.setOrientation(Qt.Horizontal)
        self.splitter_3 = QSplitter(self.splitter_4)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.label_4 = QLabel(self.splitter_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.splitter_3.addWidget(self.label_4)
        self.SelectPicButton = QPushButton(self.splitter_3)
        self.SelectPicButton.setObjectName(u"SelectPicButton")
        self.splitter_3.addWidget(self.SelectPicButton)
        self.ConvertPicButton = QPushButton(self.splitter_3)
        self.ConvertPicButton.setObjectName(u"ConvertPicButton")
        self.splitter_3.addWidget(self.ConvertPicButton)
        self.splitter_4.addWidget(self.splitter_3)
        self.label_5 = QLabel(self.splitter_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.splitter_4.addWidget(self.label_5)
        self.GenNumsState = QLabel(Pubchem_Tools)
        self.GenNumsState.setObjectName(u"GenNumsState")
        self.GenNumsState.setEnabled(True)
        self.GenNumsState.setGeometry(QRect(310, 60, 71, 21))
        self.GenNumsState.setCursor(QCursor(Qt.ForbiddenCursor))
        self.GenNumsState.setFrameShape(QFrame.WinPanel)
        self.GenNumsState.setFrameShadow(QFrame.Plain)
        self.GenNumsState.setAlignment(Qt.AlignCenter)
        self.splitter_5 = QSplitter(Pubchem_Tools)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setGeometry(QRect(60, 30, 522, 24))
        self.splitter_5.setOrientation(Qt.Horizontal)
        self.label_6 = QLabel(self.splitter_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.splitter_5.addWidget(self.label_6)
        self.NumsEdit = QLineEdit(self.splitter_5)
        self.NumsEdit.setObjectName(u"NumsEdit")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.NumsEdit.sizePolicy().hasHeightForWidth())
        self.NumsEdit.setSizePolicy(sizePolicy1)
        font1 = QFont()
        font1.setFamilies([u"Cambria"])
        font1.setPointSize(10)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setKerning(True)
        self.NumsEdit.setFont(font1)
        self.splitter_5.addWidget(self.NumsEdit)
        self.GenerateNumsButton = QPushButton(self.splitter_5)
        self.GenerateNumsButton.setObjectName(u"GenerateNumsButton")
        self.splitter_5.addWidget(self.GenerateNumsButton)
        self.label_7 = QLabel(self.splitter_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.splitter_5.addWidget(self.label_7)

        self.retranslateUi(Pubchem_Tools)

        QMetaObject.connectSlotsByName(Pubchem_Tools)
    # setupUi

    def retranslateUi(self, Pubchem_Tools):
        Pubchem_Tools.setWindowTitle(QCoreApplication.translate("Pubchem_Tools", u"pubchem\u6570\u636e\u8f6c\u5316\u5de5\u5177V1.0", None))
        self.ConvertState.setText(QCoreApplication.translate("Pubchem_Tools", u"\u8fd8\u672a\u8f6c\u5316", None))
        self.Convert2DState.setText(QCoreApplication.translate("Pubchem_Tools", u"2D\u8fd8\u672a\u8f6c\u5316", None))
        self.Convert3DState.setText(QCoreApplication.translate("Pubchem_Tools", u"3D\u8fd8\u672a\u8f6c\u5316", None))
        self.AddCasState.setText(QCoreApplication.translate("Pubchem_Tools", u"\u8fd8\u672a\u6dfb\u52a0", None))
        self.Save2DMolButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e92DMol\u5b58\u50a8\u8def\u5f84", None))
        self.Save3DMolButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e93DMol\u5b58\u50a8\u8def\u5f84", None))
        self.ConvertPicState.setText(QCoreApplication.translate("Pubchem_Tools", u"\u8fd8\u672a\u8f6c\u5316", None))
        self.label.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e9CSV\u6587\u4ef6", None))
        self.SelectCsvButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e9Csv", None))
        self.SaveExcelButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u751f\u6210Excel\u6587\u4ef6", None))
        self.AddCasToExcelButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u6dfb\u52a0cas\u5230Excel", None))
        self.label_2.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9ed8\u8ba4\u4fdd\u5b58\u5728D:/DATA/ALL_Excel", None))
        self.label_3.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e9SDF\u548cExcel\u6587\u4ef6", None))
        self.SelectSdfButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e9SDF\u6587\u4ef6", None))
        self.SelectExcelButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e9Excel\u6587\u4ef6", None))
        self.SaveMol2DButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u751f\u62102DMOL\u6587\u4ef6", None))
        self.SaveMol3DButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u751f\u62103DMol\u6587\u4ef6", None))
        self.label_4.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e9\u56fe\u7247\u6587\u4ef6\u5939", None))
        self.SelectPicButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9009\u62e9\u56fe\u7247\u6587\u4ef6\u5939", None))
        self.ConvertPicButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u5f00\u59cb\u8f6c\u5316\u56fe\u7247", None))
        self.label_5.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9ed8\u8ba4\u4fdd\u5b58D:/DATA/ALL_Pic", None))
        self.GenNumsState.setText(QCoreApplication.translate("Pubchem_Tools", u"\u8fd8\u672a\u751f\u6210", None))
        self.label_6.setText(QCoreApplication.translate("Pubchem_Tools", u"\u751f\u6210\u6570\u5b57\u6587\u672c", None))
        self.NumsEdit.setText(QCoreApplication.translate("Pubchem_Tools", u"1,10000", None))
        self.GenerateNumsButton.setText(QCoreApplication.translate("Pubchem_Tools", u"\u751f\u6210txt\u6587\u4ef6", None))
        self.label_7.setText(QCoreApplication.translate("Pubchem_Tools", u"\u9ed8\u8ba4\u4fdd\u5b58\u5728D:/DATA/nums.txt", None))
    # retranslateUi

